[package]
name = "password-generator"
version = "0.1.0"
edition = "2021"
authors = ["Lorenzo Costa <http://www.costa86.tech>"]
description = "A CLI password generator ğŸ”"
license = "AGPL-3.0-or-later"
keywords = ["cli", "password", "security"]
repository = "https://github.com/costa86/password-generator"
documentation = "https://docs.rs/password-generator/"

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
passwords = "3.1.9"
